# Generated by Django 4.1 on 2022-09-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("body_uz", models.TextField()),
                ("body_ru", models.TextField()),
                ("body_en", models.TextField()),
            ],
        ),
    ]
