# Generated by Django 4.1 on 2022-09-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_remove_template_body_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="login",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="botuser",
            name="password",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="botuser",
            name="chat_id",
            field=models.IntegerField(default=0),
        ),
    ]
