# Generated by Django 4.1 on 2022-09-18 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0004_botuser_login_botuser_password_alter_botuser_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="botuser",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
    ]
