# Generated by Django 4.1 on 2022-09-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_remove_botuser_is_used_remove_botuser_login_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CakeDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ids", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Cakes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=255)),
                ("cake_name", models.CharField(max_length=255)),
                ("cake_price", models.IntegerField()),
            ],
        ),
    ]
