# Generated by Django 4.1 on 2022-09-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_alter_cake_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="aziza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelTable(
            name="cake",
            table=None,
        ),
    ]
