# Generated by Django 4.1 on 2022-09-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_user_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user_order",
            name="ordered_date",
            field=models.CharField(max_length=255),
        ),
    ]
