# Generated by Django 4.1 on 2022-09-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0015_alter_user_order_ordered_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user_order",
            name="ordered_time",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
