# Generated by Django 4.1 on 2022-10-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0019_cake_cake_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cake",
            name="cake_photo",
            field=models.ImageField(upload_to="photos"),
        ),
    ]
