# Generated by Django 4.1 on 2022-09-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cakedescription",
            name="chat_id",
            field=models.IntegerField(default=0),
        ),
    ]
