# Generated by Django 4.1 on 2022-09-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0003_alter_total_num_num"),
    ]

    operations = [
        migrations.CreateModel(
            name="Going_to_Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.IntegerField(default=0)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
