# Generated by Django 4.1 on 2022-10-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0006_where_user_chat_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category_msg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.IntegerField(default=0)),
                ("text", models.CharField(max_length=255)),
            ],
        ),
    ]
