# Generated by Django 4.1 on 2022-10-08 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0007_category_msg"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category_msg",
            old_name="text",
            new_name="text_id",
        ),
    ]
