# Generated by Django 4.1 on 2022-10-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variables", "0008_rename_text_category_msg_text_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="category_msg",
            name="title",
            field=models.CharField(default="", max_length=255),
        ),
    ]
